[build]
  command = "pip install -r requirements.txt"
  publish = "/templates/"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/flask_app.py"
  status = 200
