[build]
  command = "pip install -r requirements.txt"
  publish = "."

[functions]
  directory = "netlify/functions"
# Let static files be served directly
[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200
  
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/flask_app.py"
  status = 200
