[build]
  command = "pip install -r requirements.txt"
  publish = "public"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/pythonapp"
  status = 200
